
let x1 = document.querySelector(".i1")
let x2 = document.querySelector(".i2")
let x3 = document.querySelector(".i3")
let x1 = document.querySelector(".s1")
let x2 = document.querySelector(".s2")
let x3 = document.querySelector(".s3")
let x1 = document.querySelector(".t1")
let x2 = document.querySelector(".t2")
let x3 = document.querySelector(".t3")